#!/usr/bin/env python3
"""
scripts/train_purifier.py  --  trains the FRPure TinyUNet (the learned defense).

Two regimes:
  default (non-adaptive): adversarials made against the BARE backbone. Fast, but
    the purifier never sees an attacker that optimizes THROUGH it -> gives ~0
    robustness under direct-gradient PGD+EOT (what we observed).
  --adaptive (min-max AT): each training adversarial is generated by attacking
    THROUGH the current purifier (Target(backbone, defense=<live purifier>)).
    The outer step then trains the purifier to restore the clean identity on
    those. This is the only thing with a chance of moving pgd_eot off zero.

  --warmup_epochs N : run N non-adaptive epochs first (cheap, stabilizes), then
    switch to adaptive. Adaptive AT can be unstable from a cold start.

losses = emb-consistency(adv) + lambda_fid*L1(purified, clean) + emb-consistency(clean)

Run (adaptive, real):
  python scripts/train_purifier.py --aligned_dir DATA/lfw_aligned_160 --backbone facenet \
      --size 160 --epochs 6 --warmup_epochs 1 --adaptive --adv_steps 7 --out results/purifier_at.pth
CPU self-test:
  python scripts/train_purifier.py --synthetic --adaptive --device cpu --iters 3
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from frpure.models.backbone import build_backbone
from frpure.attacks.base import Target, cos_sim
from frpure.attacks import gradient as G
from frpure.defenses.frpure import TinyUNet, freq_split, attack_region_mask
from frpure.defenses.vit_denoiser import ViTDenoiser


# --------------------------------------------------------------------------- #
# data
# --------------------------------------------------------------------------- #
class FaceFolder(Dataset):
    def __init__(self, root, size):
        self.paths = []
        for ext in ("png", "jpg", "jpeg"):
            self.paths += glob.glob(os.path.join(root, "**", f"*.{ext}"), recursive=True)
        self.paths.sort()
        if not self.paths:
            raise RuntimeError(f"no images under {root}")
        self.size = size

    def __len__(self): return len(self.paths)

    def __getitem__(self, i):
        from PIL import Image
        img = Image.open(self.paths[i]).convert("RGB").resize((self.size, self.size))
        return torch.from_numpy(np.asarray(img, dtype=np.float32) / 255.0).permute(2, 0, 1).contiguous()


class SyntheticFaces(Dataset):
    def __init__(self, n=32, size=64):
        g = torch.Generator().manual_seed(0)
        self.x = torch.rand(n, 3, size, size, generator=g)
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i]


# --------------------------------------------------------------------------- #
# purify forward with a TRAINABLE unet (mirrors FRPure.purify)
# --------------------------------------------------------------------------- #
def purify_train(unet, x, mask, cutoff):
    low, high = freq_split(x, cutoff)
    return (x * (1 - mask) + (low + unet(high * mask)) * mask).clamp(0, 1)


class _LiveDefense:
    """Adapter so the inner attack can differentiate through the CURRENT purifier.
    differentiable=True -> Target backprops straight through purify (adaptive)."""
    differentiable = True
    randomized = False

    def __init__(self, unet, mask, cutoff):
        self.unet, self.mask, self.cutoff = unet, mask, cutoff

    def purify(self, x01):
        return purify_train(self.unet, x01, self.mask, self.cutoff)


def train(args):
    device = args.device if (args.device == "cpu" or torch.cuda.is_available()) else "cpu"
    backbone = build_backbone(args.backbone, device=device)

    ds = SyntheticFaces(size=args.size) if args.synthetic else FaceFolder(args.aligned_dir, args.size)
    dl = DataLoader(ds, batch_size=args.batch, shuffle=True, drop_last=True)

    unet = (ViTDenoiser() if args.denoiser == "vit" else TinyUNet()).to(device).train()
    opt = torch.optim.Adam(unet.parameters(), lr=args.lr)
    mask = attack_region_mask(args.size, args.size, device)
    eps, alpha = G.DEFAULT_EPS_LINF, G.DEFAULT_ALPHA_LINF
    live = _LiveDefense(unet, mask, args.cutoff)   # shares unet weights live

    step = 0
    for epoch in range(args.epochs):
        adaptive = args.adaptive and epoch >= args.warmup_epochs
        for x in dl:
            x = x.to(device)
            with torch.no_grad():
                e_clean = backbone.embed(x)

            # generate the adversarial: through the purifier (adaptive) or against
            # the bare backbone (warmup / non-adaptive). autograd.grad inside pgd
            # returns input-grads only, so the unet's param grads stay clean here.
            tgt = Target(backbone, defense=live, bpda=False) if adaptive \
                else Target(backbone, defense=None)
            x_adv = G.pgd(tgt, x, x, eps, alpha, steps=args.adv_steps,
                          mode="dodging", n_eot=1, rand_init=True)

            # outer step: train the purifier to restore the clean identity
            x_pur = purify_train(unet, x_adv, mask, args.cutoff)
            loss_emb = (1 - cos_sim(backbone.embed(x_pur), e_clean)).mean()
            loss_fid = F.l1_loss(x_pur, x)
            x_pur_c = purify_train(unet, x, mask, args.cutoff)
            loss_clean = (1 - cos_sim(backbone.embed(x_pur_c), e_clean)).mean()
            loss = loss_emb + args.lambda_fid * loss_fid + loss_clean

            opt.zero_grad(); loss.backward(); opt.step()

            step += 1
            if step % args.log_every == 0 or args.synthetic:
                tag = "ADAPT" if adaptive else "warm "
                print(f"[{tag}] ep{epoch} step{step}  loss={loss.item():.4f} "
                      f"(emb={loss_emb.item():.4f} fid={loss_fid.item():.4f} clean={loss_clean.item():.4f})")
            if args.synthetic and step >= args.iters:
                break
        if args.synthetic and step >= args.iters:
            break

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    torch.save(unet.state_dict(), args.out)
    print(f"saved purifier -> {args.out}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--synthetic", action="store_true")
    ap.add_argument("--aligned_dir")
    ap.add_argument("--backbone", default="dummy")
    ap.add_argument("--size", type=int, default=64)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--epochs", type=int, default=5)
    ap.add_argument("--denoiser", choices=["unet", "vit"], default="unet",
                     help="purifier architecture: TinyUNet (conv) or ViTDenoiser (transformer)")
    ap.add_argument("--adaptive", action="store_true", help="min-max: attack through the purifier")
    ap.add_argument("--warmup_epochs", type=int, default=1, help="non-adaptive epochs before adaptive")
    ap.add_argument("--adv_steps", type=int, default=7, help="inner PGD steps (train cheaper than eval)")
    ap.add_argument("--cutoff", type=float, default=0.15)
    ap.add_argument("--lambda_fid", type=float, default=1.0)
    ap.add_argument("--lr", type=float, default=2e-4)
    ap.add_argument("--iters", type=int, default=3)
    ap.add_argument("--log_every", type=int, default=50)
    ap.add_argument("--out", default="results/purifier.pth")
    ap.add_argument("--device", default="cuda")
    args = ap.parse_args()
    if not args.synthetic and args.backbone == "dummy":
        args.backbone, args.size = "facenet", 160
    train(args)


if __name__ == "__main__":
    main()